package com.bankingsystem.constants;

/**
 * Defines the possible status of a request generated by a customer
 * 
 * @author Soumyadeep Ganguly
 *
 */
public enum RequestStatus {
	PENDING, REJECTED, APPROVED;
}
